### PR TITLE
Add a new readme.md, move previous readme.md

### PR DESCRIPTION
**Pull request by Plat251**
I've written a new readme.md from scratch, and cut up the previous readme into files battle.md and creatures.md, and moved it somewhere where we can conveniently store all other supplementary information for game design.

### CODE REVIEW

**Comment by morriswr01** [comment]
Could add a "Resources" section (or similar) to put links to the Trello and other useful stuff like that in.

**Comment by Plat251** [comment]
This should end up resolving Issue #7 when approved.

**Comment by RedRoyalDog** [comment]
You could merge #6 into this as the better readme that you moved.

**Comment by Plat251** [comment]
The problem is that before I moved and cut up the old readme.md, I fixed the markdown as well. There is very little, if anything, to be gained with such a merge.

**Comment by Plat251** [comment]
Now it's definitely marked down properly everywhere.

**Pull request merged**
